description: HAHAHA
#
# A100
# Steps:  45% 900/2000 [20:55<18:58,  1.03s/it, GPU=15132, Loss/pred=0.122, Loss/prior=0.372, Loss/total=0.247, lr/text=1.96e-5, lr/unet=0.000784]
#
pretrained_model_name_or_path: runwayml/stable-diffusion-v1-5
pretrained_vae_name_or_path: stabilityai/sd-vae-ft-mse
pretrained_tokenizer_name_or_path: null
revision: null
#
#
train_unet_module_or_class: [ff]
train_unet_submodule: null
#
train_text_module_or_class: [mlp]
train_text_submodule: null
#
lora_unet_layer: [Linear]
lora_unet_train_off_target: null
lora_unet_rank: 16
lora_unet_alpha: 4.0
#
lora_text_layer: [Linear]
lora_text_train_off_target: [Embedding]
lora_text_rank: 4
lora_text_alpha: 4.0
#
#
add_instance_token: false
#
#
instance_token: caetmux
instance_prompt: a photo of {} person
instance_data_dir: /content/gdrive/MyDrive/InstanceImages/cm2
prompt_templates: null
class_data_dir: /content/gdrive/MyDrive/RegularizationImages/person
class_token: person
class_prompt: a photo of a person
with_prior_preservation: true
prior_loss_weight: 1.0
num_class_images: 1500
sample_batch_size: 4
use_instance_image_captions: true
use_class_image_captions: false
#
#
conditioning_dropout_prob: 0.0
unconditional_prompt: ' '
clip_skip: null
#
#
augment_output_dir: null
augment_min_resolution: 580
augment_center_crop: false
augment_hflip: false
augment_trivialwide: false
#
#
seed: 1275017
enable_full_determinism: false
resolution: 512
mixed_precision: fp16
train_batch_size: 8
max_train_steps: 1000
gradient_accumulation_steps: 1
gradient_checkpointing: true
enable_xformers: true
#
#
loss: mse
optimizer: QHAdam
optimizer_params: 'lr=1e-4;betas=(0.9, 0.999);weight_decay=0.0;eps=1.0e-08'
max_grad_norm: 1.0
#
#
lr_scheduler: cosine
lr_scale: false
lr_unet: 5e-4
lr_text: 2.0e-05
separate_token_embedding: false
lr_token_embedding: 1e-6
#
lr_scheduler_params: 'num_warmup_steps=0'
#
#
use_ema: false
ema_inv_gamma: 1.0
ema_power: 0.75
ema_min_value: 0.0
ema_max_value: 0.9999
#
#
output_dir: /content/models/
logging_dir: /content/logs/
#
#
save_n_sample: 4
save_interval: 100
save_min_steps: 100
save_parameter_summary: true
save_model_layout: false
#
sample_prompt: a photo of a person // a photo of Keanu Reeves // a photo of {}
  person // an painting of {} person by Picasso
sample_negative_prompt: hands, border
sample_seed: null
sample_guidance_scale: 7.5
sample_infer_steps: 50
#
#
hub_token: null
hub_model_id: null
push_to_hub: false
#
#
local_rank: -1
#
#
log_gpu: true
debug: false
