description: textual inversion w/ pivotal tuning example configuration
#
# T4
# train_batch_size: 1, gradient_checkpointing: false, gradient_accumulation_steps: 1
# Steps:   5% 102/2000 [01:01<16:30,  1.92it/s, GPU=6758, Loss/pred=0.0193, lr/text=0, lr/token=0.0005]
#
pretrained_model_name_or_path: runwayml/stable-diffusion-v1-5
pretrained_vae_name_or_path: null
pretrained_tokenizer_name_or_path: null
revision: null
#
#
train_unet_module_or_class: null
train_unet_submodule: null
#
train_text_module_or_class: [mlp, embeddings]
train_text_submodule: [fc1, fc2, token_embedding]
#
lora_unet_layer: null
lora_unet_train_off_target: null
lora_unet_rank: 4
lora_unet_alpha: 4.0
#
lora_text_layer: [Linear]
lora_text_train_off_target: [Embedding]
lora_text_rank: 1
lora_text_alpha: 4.0
#
#
add_instance_token: true
#
#
instance_token: <cat-toy>
instance_prompt: a photo of {}
instance_data_dir: /content/gdrive/MyDrive/cat_statue
prompt_templates: object
class_data_dir: null
class_token: toy
class_prompt: a photo of a toy
with_prior_preservation: false
prior_loss_weight: 1.0
num_class_images: 1500
sample_batch_size: 4
use_instance_image_captions: false
use_class_image_captions: false
#
#
conditioning_dropout_prob: 0.0
unconditional_prompt: ' '
clip_skip: null
#
#
augment_output_dir: null
augment_min_resolution: null
augment_center_crop: false
augment_hflip: false
augment_trivialwide: false
#
#
seed: 1275017
enable_full_determinism: false
resolution: 512
mixed_precision: fp16
train_batch_size: 1
max_train_steps: 2000
gradient_accumulation_steps: 1
gradient_checkpointing: false
enable_xformers: true
#
#
loss: mse
optimizer: AdamW8bit
optimizer_params: 'lr=1e-4;betas=(0.9, 0.999);weight_decay=1e-5;eps=1.0e-08'
max_grad_norm: 1.0
#
#
lr_scheduler: multi_explore_exploit
lr_scale: false
lr_unet: 1e-5
lr_text: 1e-5
separate_token_embedding: true
lr_token_embedding: 5e-4
#
lr_scheduler_params: 'start_step=(0,600);num_warmup_steps=(0,0);num_explore_steps=(500,1000);num_total_steps=(600,2000)'
#
lr_inversion_fraction: 0.5
lr_overlap_fraction: 0.25
#
#
use_ema: false
ema_inv_gamma: 1.0
ema_power: 0.75
ema_min_value: 0.0
ema_max_value: 0.9999
#
#
output_dir: /content/models/
logging_dir: /content/logs/
#
#
save_n_sample: 4
save_interval: 200
save_min_steps: 200
save_parameter_summary: true
save_model_layout: false
#
sample_prompt: a photo of {} // a photo of {} holding a mug // an painting of {} by Picasso
sample_negative_prompt: border
sample_seed: null
sample_guidance_scale: 7.5
sample_infer_steps: 50
#
#
hub_token: null
hub_model_id: null
push_to_hub: false
#
#
local_rank: -1
#
#
log_gpu: true
debug: false
